const fs = require("fs");
const { Document, Packer, Paragraph, AlignmentType, BorderStyle, PageBreak } = require("docx");
const H = require("../class01/build_docx_helpers.js");
const { t, body, lead, h1, h2, mr, sub, sup, sum, eq, eqL, table, gap } = H;

const IN="∈", LE="≤", GE="≥", NE="≠", SUBSET="⊂",
      R="ℝ", DELTA="δ", OMEGA="ω", CAPOMEGA="Ω",
      PI="π", SIGMA="σ", NOTIN="∉", MINUS="−",
      UNION="∪", INF="∞", LAMBDA="λ", QQ="ℚ";

const ch = [];
const P = (...xs) => xs.forEach(x => ch.push(x));
const brk = () => new Paragraph({ children: [new PageBreak()] });

// ---------------------------------------------------------------- title
P(
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:70},
   children:[t("IE 5311-001 (D01)  Principles of Optimization",{bold:true,size:32})]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:70},
   children:[t("Homework Solutions",{size:27})]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:50},
   children:[t("Problems 1–4 and Exploration Problems EP1, EP2")]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:50},
   children:[t("Lidivine Kengne")]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:240},
   border:{bottom:{style:BorderStyle.SINGLE,size:6,color:"000000",space:8}},
   children:[t("Fall 2026   |   Instructor: Ningji Wei")]}),
 body("All models are stated in general indexed form: sets, parameters with units, decision variables with domains, a summed objective, and each constraint written once under a quantifier. Every numerical result was produced with Gurobi 13.0.3 in Python unless noted, and each was checked against an independent calculation that does not use the same solver."),
);

// =============================================== PROBLEM 1
P(brk(), h1("Problem 1.  Maya's Investment Plan  [20 pts]"),
 h2("1.1  Time convention"),
 body("Let period t index the BEGINNING of year t, so t runs 1 to 5, and let t = 6 denote the end of Year 5, the moment the objective is measured. An instrument of term L started at epoch t matures at epoch t + L and is admissible only if t + L ≤ 6. Fixing this convention first is what determines which instruments appear at which epochs, and it is the step where the problem is most easily got wrong."),
 h2("1.2  Sets"),
 table([1150,6530],[["Symbol","Definition"],
  ["T = {1,…5}","Decision epochs, the beginning of each year"],
  ["K = {1,2,3}","Instrument types, indexed by their term in years"],
  ["A","Admissible pairs (t,k) with t ≥ aₖ and t + Lₖ ≤ 6"]]), gap(),
 h2("1.3  Parameters"),
 table([1150,4600,1930],[["Symbol","Definition","Value"],
  ["Lₖ","Term of instrument k","1, 2, 3 years"],
  ["rₖ","Total return multiplier over the full term","1.04, 1.09, 1.15"],
  ["aₖ","First epoch at which instrument k is available","1, 1, 2"],
  ["B","Initial endowment","$5,000"],
  ["H","Horizon epoch","6"]]), gap(),
 body("Pioneer's three-year certificate carries a₃ = 2 because it opens at the beginning of Year 2. Combined with t + 3 ≤ 6 this leaves exactly two admissible start epochs for it, t = 2 and t = 3."),
 h2("1.4  Decision variables"),
 eq([sub("x","t,k"), mr(` ${GE} 0  = dollars placed at epoch t into an instrument of term k`)]),
 eq([sub("w","t"), mr(` ${GE} 0  = dollars held idle from epoch t to epoch t+1`)]),
 body("The idle-cash variables are included deliberately. Every instrument earns a positive return, so I expect them all to be zero at the optimum; keeping them in the model makes full reinvestment a result rather than an assumption baked into the formulation."),
 h2("1.5  Model"),
 eqL([mr("max  "), sum(`(t,k) ${IN} A : t+Lₖ = H`,[sub("r","k"), sub("x","t,k")]), mr("  +  "), sub("w","5")]),
 body("subject to"),
 eqL([sum(`k`,[sub("x","1,k")]), mr("  +  "), sub("w","1"), mr("  =  B")],"epoch 1"),
 eqL([sum(`k`,[sub("x","t,k")]), mr("  +  "), sub("w","t"), mr("  =  "),
      sum(`(s,k) : s+Lₖ = t`,[sub("r","k"), sub("x","s,k")]), mr("  +  "), sub("w","t−1")],"t = 2,…,5"),
 eqL([sub("x","t,k"), mr(` ${GE} 0,    `), sub("w","t"), mr(` ${GE} 0`)]),
 gap(),
 body("The balance constraints are flow conservation on a timeline: what matures at epoch t, plus whatever was carried forward, is exactly what gets allocated at epoch t."),
 h2("1.6  Result"),
 body("There are 11 admissible (epoch, instrument) pairs. The optimal value is $6,267.50."),
 table([1400,1700,2100,2480],[["Epoch","Term","Amount","Matures at"],
  ["1","2 years","$5,000.00","epoch 3"],
  ["3","3 years","$5,450.00","epoch 6"]]), gap(),
 body("No idle cash is held at any epoch, which confirms the expectation above. The plan is: a two-year deposit covering Years 1 and 2 returning 5,000 × 1.09 = $5,450, then the Pioneer three-year certificate covering Years 3 to 5 returning 5,450 × 1.15 = $6,267.50."),
 h2("1.7  Verification"),
 body("I checked this without the LP. Because every instrument has a fixed term, any admissible plan is a sequence of terms that exactly tiles epochs 1 to 6, and its payoff is the product of the corresponding multipliers times B. Enumerating all 11 such sequences and taking the best gives $6,267.50, matching the LP to the cent."),
 table([2600,2100,2980],[["Multiplier","Final value","Plan (epoch, term)"],
  ["1.253500","$6,267.50","(1, 2yr), (3, 3yr)"],
  ["1.243840","$6,219.20","(1, 1yr), (2, 3yr), (5, 1yr)"],
  ["1.243840","$6,219.20","(1, 1yr), (2, 1yr), (3, 3yr)"],
  ["1.235624","$6,178.12","(1, 2yr), (3, 2yr), (5, 1yr)"]]), gap(),
 lead("Why the winner wins.","Compare instruments on an annualized basis: the one-year pays 4.000% per year, the two-year pays 1.09^(1/2) − 1 = 4.403%, and the three-year pays 1.15^(1/3) − 1 = 4.769%. The three-year is best per year, so the plan wants as much time as possible inside it. Its 3-year term and its a₃ = 2 availability mean it can only occupy epochs 2–5 or 3–6. Taking 3–6 leaves epochs 1–3 to be covered, and a single two-year deposit covers them better than two one-year deposits, since 1.09 > 1.04² = 1.0816."),
 lead("Shadow prices.","The dual on the epoch-1 balance is 1.2535, exactly the compounded multiplier of the winning plan: one extra dollar at the start is worth $1.2535 at the horizon. The duals at epochs 2 to 5 are 1.1960, 1.1500, 1.0900 and 1.0400, each the best multiplier still reachable from that epoch. That the epoch-5 dual is 1.04, the one-year rate, is a useful consistency check, because a one-year deposit is the only instrument left at epoch 5."),
);

// =============================================== PROBLEM 2
P(brk(), h1("Problem 2.  Shortest and Longest s–t Paths  [40 pts]"),
 h2("2.1  Instance generation"),
 body(`Ten directed graphs were generated with NetworkX using the G(n,p) model with |V| = 20, source s = 0 and terminal t = 19. Each arc weight cᵢⱼ was drawn uniformly from [1,10]. Generation rejects and retries, raising p, until the graph is weakly connected and NetworkX confirms an s–t path exists, so both required properties hold by construction rather than by luck. The ten instances carry between 58 and 90 arcs.`),
 h2("2.2  Common sets and parameters"),
 table([1250,6430],[["Symbol","Definition"],
  ["V","Nodes, |V| = 20, with source s and terminal t"],
  [`A ${SUBSET} V × V`,"Directed arcs, a typical arc written (i,j)"],
  [`${DELTA}⁺(i), ${DELTA}⁻(i)`,"Out- and in-neighborhoods of node i"],
  ["cᵢⱼ","Weight of arc (i,j), drawn from U[1,10]"],
  ["bᵢ","+1 at s, −1 at t, 0 at every other node"]]), gap(),
 eq([sub("x","ij"), mr(" = 1 if arc (i,j) is used, 0 otherwise")]),

 h2("2.3 (a)  Shortest path formulation"),
 eqL([mr("min  "), sum(`(i,j) ${IN} A`,[sub("c","ij"), sub("x","ij")])]),
 body("subject to"),
 eqL([sum(`j ${IN} ${DELTA}⁺(i)`,[sub("x","ij")]), mr(` ${MINUS} `),
      sum(`j ${IN} ${DELTA}⁻(i)`,[sub("x","ji")]), mr(" = "), sub("b","i")],`for all i ${IN} V`),
 eqL([sub("x","ij"), mr(` ${IN} {0,1}`)],`for all (i,j) ${IN} A`),
 gap(),
 body("Flow conservation alone suffices. A feasible integer point decomposes into an s–t path plus possibly some directed cycles that are arc-disjoint from it; since every weight is at least 1, dropping a cycle strictly lowers the objective, so no optimal solution contains one. This argument depends on the weights being positive and would fail if negative weights were allowed."),
 h2("2.4 (b, c)  Integer model and LP relaxation"),
 body(`The relaxation replaces the binary domain with 0 ${LE} xᵢⱼ ${LE} 1. Before running anything I expected the two to return identical objective values on all ten instances. The constraint matrix is the node-arc incidence matrix of a directed graph, which is totally unimodular, and the right-hand side vector b is integral, so by the Hoffman and Kruskal theorem every vertex of the relaxed polytope is integral. EP1 below develops this argument in full.`),
 h2("2.5 (d)  Comparison over the ten instances"),
 table([700,700,1400,1400,1200,1200,1080],
  [["Inst","|A|","MIP objective","LP objective","MIP time (s)","LP time (s)","B&B nodes"],
   ["1","59","10.4591","10.4591","0.0262","0.0003","1"],
   ["2","81","9.9972","9.9972","0.0261","0.0002","1"],
   ["3","61","8.3409","8.3409","0.0004","0.0001","0"],
   ["4","90","14.5495","14.5495","0.0123","0.0002","1"],
   ["5","73","22.2423","22.2423","0.0108","0.0002","1"],
   ["6","67","15.1332","15.1332","0.0014","0.0002","1"],
   ["7","58","13.6582","13.6582","0.0013","0.0002","1"],
   ["8","72","23.5501","23.5501","0.0012","0.0002","1"],
   ["9","80","9.8539","9.8539","0.0010","0.0002","1"],
   ["10","63","3.0157","3.0157","0.0015","0.0002","1"]]), gap(),
 lead("Findings.","The integrality gap is zero on all ten instances; the largest discrepancy is 3.55 × 10⁻¹⁵, which is floating-point noise rather than a gap. No arc variable took a fractional value in any relaxed solution. Branch and bound explored at most one node, meaning the root relaxation was already integral and no branching occurred. The relaxation solved about 39 times faster on average, and that ratio is mostly fixed overhead in setting up the branch-and-bound machinery rather than genuine search."),
 body("The practical implication is that the binary declaration is redundant here. On a network this shape you should solve the linear program and take the answer, and at realistic sizes the specialized algorithms (Dijkstra, Bellman-Ford) beat both. What the experiment confirms is a structural property, not a performance recommendation."),

 h2("2.6 (a)  Longest simple path formulation"),
 eqL([mr("max  "), sum(`(i,j) ${IN} A`,[sub("c","ij"), sub("x","ij")])]),
 body("subject to"),
 eqL([sum(`j ${IN} ${DELTA}⁺(i)`,[sub("x","ij")]), mr(` ${MINUS} `),
      sum(`j ${IN} ${DELTA}⁻(i)`,[sub("x","ji")]), mr(" = "), sub("b","i")],`for all i ${IN} V`),
 eqL([sum(`j ${IN} ${DELTA}⁺(i)`,[sub("x","ij")]), mr(` ${LE} 1`)],`for all i ${IN} V`),
 eqL([sum(`(i,j) ${IN} A(S)`,[sub("x","ij")]), mr(` ${LE} |S| ${MINUS} 1`)],
     `for all S ${SUBSET} V\\{s,t}, |S| ${GE} 2`),
 eqL([sub("x","ij"), mr(` ${IN} {0,1}`)],`for all (i,j) ${IN} A`),
 gap(),
 body("The out-degree restriction enforces “visiting each location at most once”. The subtour elimination family is mandatory here and this is the substantive difference from the shortest path model. Under minimization a stray cycle only adds cost and disappears on its own. Under maximization every cycle adds weight for free, so the model without that family returns an s–t path plus as many disjoint cycles as the degree limits permit."),
 lead("Measured confirmation.","On instance 1 the master problem with no subtour constraint returns 107.1629, selecting 19 arcs that contain three separate cycles: {11,15}, {17,18,2} and {1,10,16,12,9,7,14}. The true longest simple path is 98.6059. The unconstrained model overstates it by 8.5570 and its answer is not a path at all."),

 h2("2.7 (b, c)  Two generation strategies"),
 lead("Constraint generation.","Solve the master to proven optimality with the subtour constraints found so far. Inspect the incumbent, detect every simple cycle among the selected arcs, add the corresponding constraint for each, and re-solve from scratch. Each round is a complete branch-and-bound run."),
 lead("Lazy constraints.","Run a single branch-and-bound search. A callback fires at every integer-feasible incumbent (Gurobi's MIPSOL event), detects cycles in that incumbent, and injects the violated constraints through cbLazy. The search continues from where it was, keeping its tree, bounds and pseudo-costs."),

 h2("2.8 (d)  Comparison over the ten instances"),
 table([620,1180,1180,900,900,900,900,1100],
  [["Inst","CG objective","Lazy objective","CG time (s)","Lazy time (s)","CG rounds","CG cuts","Lazy cuts"],
   ["1","98.6059","98.6059","0.0446","0.0345","6","9","16"],
   ["2","96.4163","96.4163","2.6200","0.0651","59","66","87"],
   ["3","8.3409","8.3409","10.4500","0.1002","215","227","227"],
   ["4","135.2684","135.2684","2.5587","0.0740","53","65","116"],
   ["5","104.4747","104.4747","1.5418","0.0458","60","67","71"],
   ["6","121.4952","121.4952","0.2925","0.0289","28","29","33"],
   ["7","92.6552","92.6552","0.4299","0.0382","34","37","45"],
   ["8","120.5135","120.5135","0.0182","0.0067","6","10","10"],
   ["9","86.8009","86.8009","20.7399","0.1781","204","231","266"],
   ["10","87.6195","87.6195","1.8177","0.0520","74","77","80"]]), gap(),
 lead("Findings.","The two methods return identical objective values on all ten instances, as they must, since both converge to the same fully-constrained problem. The lazy method is 65 times faster on average. Constraint generation required 739 complete master re-solves in total across the ten instances, against ten branch-and-bound runs for the lazy method."),
 lead("The instance that surprised me.","Instance 3 was the worst case for constraint generation, needing 215 rounds, yet its optimal value 8.3409 is identical to its shortest path value. I expected the hardest instance to be a dense one with many competing paths. Enumerating all simple s–t paths explains it: instance 3 has exactly one, namely 0 → 11 → 19, so the shortest and longest paths must coincide. The 215 rounds were not spent choosing between paths. They were spent eliminating cycles elsewhere in the graph before the model was forced onto the only path available. Difficulty here tracks the number of cycles the master can chase, not the number of paths that compete."),
 body("As a further check, full enumeration of simple s–t paths on instances 1 and 9 (870 and 2,491 paths respectively) reproduces both the minimum and the maximum returned by the solvers exactly."),

 h2("2.9 (e)  Algorithmic differences"),
 body("The difference is where the work is thrown away."),
 body("Constraint generation treats the solver as a black box. Every round starts a fresh branch-and-bound search that must rediscover the same bounds, the same branching decisions and the same cuts as the previous round, only to be told about one more constraint at the end. The cost per round grows as the master accumulates constraints, so the later rounds are the expensive ones."),
 body("Lazy constraints put the separation inside the search. One tree is built and kept. When an incumbent turns out to violate a constraint, it is rejected and the constraint is added, but the tree, its bounds, its pseudo-costs and its already-proven prunings all survive. That is the entire source of the 65x difference measured above, and it widens as instances grow."),
 body("Two costs come with the lazy method. The callback runs inside the solver, so separation must be fast, and a slow detection routine is paid at every incumbent. The solver must also be told in advance (LazyConstraints = 1), which disables some presolve reductions that would otherwise be unsafe, since presolve cannot know about constraints that do not exist yet. Constraint generation keeps full presolve on every round. On these instances that trade is decisively in favour of lazy, but it is a trade, not a free improvement."),
);

// =============================================== PROBLEM 3
P(brk(), h1("Problem 3.  GlobalLogix Distribution Network  [45 pts]"),
 h2("3.1  Sets"),
 table([1250,6430],[["Symbol","Definition"],
  ["F = {f₁, f₂}","Factories"],["D = {d₁, d₂}","Distribution centres, pure transshipment"],
  ["S = {s₁, s₂, s₃}","Stores"],["N = F ∪ D ∪ S","All nodes, indexed by i and j"],
  ["A₁ = F × D","Factory-to-DC arcs"],["A₂ = D × S","DC-to-store arcs"],
  ["A = A₁ ∪ A₂","All arcs"]]), gap(),
 h2("3.2  Parameters"),
 table([1250,4600,1830],[["Symbol","Definition","Units"],
  ["bᵢ","Net supply: +70 at f₁, +50 at f₂, −40/−45/−35 at stores, 0 at DCs","units"],
  ["uᵢⱼ","Capacity of arc (i,j)","units"],
  ["cᵢⱼ","Cost per unit shipped on arc (i,j)","$/unit"]]), gap(),
 body("Total supply is 120 and total demand is 120, so the bᵢ sum to zero and a feasible flow can exist. The DCs carry bᵢ = 0, which is exactly what “do not generate or consume products” means in the model."),
 h2("3.3 (1)  Deterministic formulation"),
 eqL([mr("min  "), sum(`(i,j) ${IN} A`,[sub("c","ij"), sub("x","ij")])]),
 body("subject to"),
 eqL([sum(`j : (i,j) ${IN} A`,[sub("x","ij")]), mr(` ${MINUS} `),
      sum(`j : (j,i) ${IN} A`,[sub("x","ji")]), mr(" = "), sub("b","i")],`for all i ${IN} N`),
 eqL([mr(`0 ${LE} `), sub("x","ij"), mr(` ${LE} `), sub("u","ij")],`for all (i,j) ${IN} A`),
 gap(),
 lead("Result.","Minimum cost $415.00."),
 table([1900,1200,1000,1300,1200,1080],
  [["Arc","Flow","Capacity","Cost/unit","Cost","Status"],
   ["(f₁, d₁)","60.0","60","2","120.0","at capacity"],
   ["(f₁, d₂)","10.0","50","4","40.0",""],
   ["(f₂, d₂)","50.0","60","1","50.0",""],
   ["(d₁, s₂)","40.0","40","1","40.0","at capacity"],
   ["(d₁, s₃)","20.0","40","2","40.0",""],
   ["(d₂, s₁)","40.0","40","2","80.0","at capacity"],
   ["(d₂, s₂)","5.0","40","3","15.0",""],
   ["(d₂, s₃)","15.0","40","2","30.0",""]]), gap(),
 body("I verified this by hand using delivered-cost-per-unit along each factory-DC-store route. The cheapest routes are f₁→d₁→s₂ and f₂→d₂→s₁ and f₂→d₂→s₃, all at $3 per unit. Loading those to their capacity limits, then filling the remainder on the next-cheapest routes, reproduces the flows in the table and the total $415.00 exactly."),

 h2("3.4 (2a)  Robust formulation, worst case"),
 body("The uncertainty set is a box: each cᵢⱼ lies in [0.99cᵢⱼ, 1.01cᵢⱼ] and each uᵢⱼ in [0.99uᵢⱼ, 1.01uᵢⱼ]. The robust problem is"),
 eq([mr("min"), sub("x","")," ", mr("max"), sub("(c,u) ",`${IN} U`), mr("  "),
     sum(`(i,j) ${IN} A`,[sub("c","ij"), sub("x","ij")])]),
 body("subject to flow conservation and to the capacity bound holding for every realization. Both inner problems have closed-form answers, so no inner optimization is needed. Cost enters the objective with a positive coefficient and x ≥ 0, so the worst case is the upper cost bound. The capacity constraint must hold for every realization, so the binding bound is the lowest capacity. The robust counterpart is therefore an ordinary linear program:"),
 eqL([mr("min  "), sum(`(i,j) ${IN} A`,[mr("1.01 "), sub("c","ij"), sub("x","ij")])]),
 eqL([mr(`0 ${LE} `), sub("x","ij"), mr(` ${LE} 0.99 `), sub("u","ij")],`for all (i,j) ${IN} A`),
 gap(),
 lead("Result.","Worst-case cost $421.57, a premium of $6.57 or 1.58% over the deterministic solution."),
 lead("What surprised me.","I expected the robust routing to match the deterministic routing with a 1% price mark-up, since a uniform 1.01 scaling of all costs cannot change which route is cheapest. It does not match. The robust plan opens a new arc, (d₁, s₁), carrying 0.4 units. The reason is the capacity side, not the cost side: shrinking every capacity by 1% removes 0.4 units of throughput from (d₂, s₁), which was at its limit, and that shortfall has to be picked up somewhere. Worst-case protection changed the structure of the plan, not just its price. Note also that 1.58% exceeds the 1% cost inflation, and the excess is precisely the cost of that forced rerouting."),

 h2("3.5 (2b)  Stochastic formulation, average case"),
 body("A stochastic program only differs from a deterministic one if some decision must be made before the uncertainty is observed. I therefore split the decision by timing. The long-haul factory-to-DC shipments are committed first, before the realization is known. The local DC-to-store deliveries are chosen afterwards, once capacities and costs are observed. Unmet demand is penalised at p per unit, which keeps the recourse problem feasible in every scenario."),
 table([1250,6430],[["Symbol","Definition"],
  [`${CAPOMEGA}`,`Scenario set, indexed by ${OMEGA}, with probability ${PI}_${OMEGA} = 1/|${CAPOMEGA}|`],
  [`c^${OMEGA}, u^${OMEGA}`,`Cost and capacity realized in scenario ${OMEGA}`],
  ["p","Penalty per unit of unmet demand, $/unit"]]), gap(),
 eq([sub("x","ij"), mr(` ${GE} 0  first stage, (i,j) ${IN} A₁;   `),
     sub("y","ij"), sup("","ω"), mr(` ${GE} 0  recourse, (i,j) ${IN} A₂;   `),
     sub("v","k"), sup("","ω"), mr(` ${GE} 0  unmet demand`)]),
 eqL([mr("min  "), sum(`(i,j) ${IN} A₁`,[sub("c","ij"), sub("x","ij")]), mr("  +  "),
      sum(`${OMEGA} ${IN} ${CAPOMEGA}`,[sub(PI,OMEGA), mr(" ( "),
        sum(`(j,k) ${IN} A₂`,[sub("c","jk"), sup("","ω"), sub("y","jk"), sup("","ω")]),
        mr(" + p "), sum(`k ${IN} S`,[sub("v","k"), sup("","ω")]), mr(" )")])]),
 body("subject to"),
 eqL([sum(`j`,[sub("x","ij")]), mr(` ${LE} `), mr("supply at i")],`for all i ${IN} F`),
 eqL([sub("x","ij"), mr(` ${LE} 0.99 `), sub("u","ij")],`for all (i,j) ${IN} A₁`),
 eqL([sum(`i`,[sub("x","ij")]), mr(" = "), sum(`k`,[sub("y","jk"), sup("","ω")])],`for all j ${IN} D, ${OMEGA} ${IN} ${CAPOMEGA}`),
 eqL([sum(`j`,[sub("y","jk"), sup("","ω")]), mr(" + "), sub("v","k"), sup("","ω"), mr(" = "), mr("demand at k")],`for all k ${IN} S, ${OMEGA} ${IN} ${CAPOMEGA}`),
 eqL([mr(`0 ${LE} `), sub("y","jk"), sup("","ω"), mr(` ${LE} `), sub("u","jk"), sup("","ω")],`for all (j,k) ${IN} A₂, ${OMEGA} ${IN} ${CAPOMEGA}`),
 gap(),
 body("The first-stage capacity bound uses 0.99uᵢⱼ rather than a scenario value. A shipment committed before the capacity is observed must fit in every realization, so that bound is robust even inside a stochastic model."),
 h2("3.6 (2b continued)  Solution and the solver ceiling"),
 body("Each parameter is drawn independently as +1% or −1% with probability one half, matching “equally likely”. The model has 4 + 9|Ω| variables and 2 + 11|Ω| constraints, so it exceeds the 2,000-variable Gurobi size-limited licence beyond |Ω| = 181. I solved the larger samples with CBC through PuLP and cross-checked at 50 scenarios, where both solvers fit: both return $416.6190."),
 table([1400,1400,2200,1400,1280],
  [["Scenarios","Solver","Expected cost","E[unmet]","Variables"],
   ["1","Gurobi","$415.58","0.0000","13"],
   ["10","Gurobi","$416.12","0.0000","94"],
   ["50","Gurobi","$416.62","0.0000","454"],
   ["150","Gurobi","$416.46","0.0000","1,354"],
   ["500","CBC","$416.40","0.0000","4,504"],
   ["2,000","CBC","$416.44","0.0000","18,004"]]), gap(),
 lead("Findings.","The expected cost settles around $416.44, between the deterministic $415.00 and the robust $421.57. That ordering is the sanity check and it holds: average-case protection costs less than worst-case protection and more than assuming nothing goes wrong. Expected unmet demand is zero at every sample size, because a 1% capacity swing is small enough that the recourse stage always absorbs it."),
 lead("Something worth stating explicitly.","The cost randomness contributes nothing. E[cᵢⱼ] = ½(0.99cᵢⱼ) + ½(1.01cᵢⱼ) = cᵢⱼ exactly, and expectation is linear, so replacing every cost by its mean reproduces the deterministic problem and its $415.00 answer to the cent. Only the capacity randomness makes the stochastic model differ from the nominal one, and only because the first-stage shipment is committed before capacity is observed. A symmetric mean-zero perturbation of objective coefficients alone never changes a risk-neutral stochastic linear program."),

 h2("3.7 (3)  Multicommodity extension"),
 body("Add a commodity index. Let P be the set of product lines, indexed by q, with P = {Standard, Premium} in the stated case."),
 table([1250,6430],[["Symbol","Definition"],
  ["P","Product lines, indexed by q"],
  ["bᵢᵠ","Net supply of product q at node i, units; positive at factories, negative at stores, zero at DCs"],
  ["cᵢⱼᵠ","Cost per unit of product q shipped on arc (i,j), $/unit"],
  ["uᵢⱼ","Capacity of arc (i,j), SHARED across products, units"]]), gap(),
 eq([sub("x","ij"), sup("","q"), mr(` ${GE} 0 = units of product q shipped on arc (i,j)`)]),
 eqL([mr("min  "), sum(`q ${IN} P`,[sum(`(i,j) ${IN} A`,[sub("c","ij"), sup("","q"), sub("x","ij"), sup("","q")])])]),
 body("subject to"),
 eqL([sum(`j : (i,j) ${IN} A`,[sub("x","ij"), sup("","q")]), mr(` ${MINUS} `),
      sum(`j : (j,i) ${IN} A`,[sub("x","ji"), sup("","q")]), mr(" = "), sub("b","i"), sup("","q")],
     `for all i ${IN} N, q ${IN} P`),
 eqL([sum(`q ${IN} P`,[sub("x","ij"), sup("","q")]), mr(` ${LE} `), sub("u","ij")],`for all (i,j) ${IN} A`),
 eqL([sub("x","ij"), sup("","q"), mr(` ${GE} 0`)],`for all (i,j) ${IN} A, q ${IN} P`),
 gap(),
 body("The structural point is the difference between the two constraint families. Flow conservation is written once per product, so it decomposes: without the second family the problem would split into |P| independent single-commodity problems, each solvable separately. The capacity constraint is written once per arc and sums across products, and it is the only thing coupling them. That single family is what makes multicommodity flow harder than |P| separate flow problems, and it is also why the linear relaxation of a multicommodity integer flow problem is generally not integral even though each single-commodity piece would be."),
);

// =============================================== PROBLEM 4
P(brk(), h1("Problem 4.  Sudoku  [30 pts]"),
 h2("4.1 (1)  Formulation with linear constraints and binary variables"),
 table([1250,6430],[["Symbol","Definition"],
  ["R = C = V = {1,…9}","Rows, columns, digit values"],
  ["B = {1,…9}","The nine 3×3 sub-blocks"],
  ["cells(b)","The nine cells belonging to block b"],
  ["G","Given clues: (r,c,v) ∈ G means cell (r,c) is pre-filled with digit v"]]), gap(),
 eq([sub("x","r,c,v"), mr(` ${IN} {0,1} = 1 if cell (r,c) holds digit v`)]),
 body("The problem is pure feasibility, so a constant objective is used. Every rule becomes an equality."),
 eqL([sum(`v ${IN} V`,[sub("x","r,c,v")]), mr(" = 1")],`for all r ${IN} R, c ${IN} C`),
 eqL([sum(`c ${IN} C`,[sub("x","r,c,v")]), mr(" = 1")],`for all r ${IN} R, v ${IN} V`),
 eqL([sum(`r ${IN} R`,[sub("x","r,c,v")]), mr(" = 1")],`for all c ${IN} C, v ${IN} V`),
 eqL([sum(`(r,c) ${IN} cells(b)`,[sub("x","r,c,v")]), mr(" = 1")],`for all b ${IN} B, v ${IN} V`),
 eqL([sub("x","r,c,v"), mr(" = 1")],`for all (r,c,v) ${IN} G`),
 gap(),
 body("All four structural families are needed and none is redundant. The first says each cell holds exactly one digit; it says nothing about uniqueness. The other three are the three uniqueness rules, one per direction. Writing them as equalities rather than ≤ 1 is what makes the count work: nine cells and nine digits means “at most once” and “exactly once” coincide, and equalities give the solver tighter information."),
 lead("Model size.","729 binary variables and 346 constraints, being 81 cell equations, 81 row, 81 column and 81 block equations, plus 22 clue fixings."),
 h2("4.2 (2, 3)  Solution of the given instance"),
 body("The instance carries 22 clues. For reference, 17 is the proven minimum number of clues for a uniquely solvable Sudoku (McGuire, Tugemann and Civario, 2012), so 22 is above that threshold but says nothing by itself about whether this particular instance is unique."),
 body("Given instance, then solution:"),
 table([700,700,700,700,700,700,700,700,700],
  [["","","2","","","5","","",""],
   ["","","1","6","","2","","",""],
   ["9","3","8","","","","","",""],
   ["","","","","7","4","","6",""],
   ["","7","","","","","2","",""],
   ["3","","","","","","","1",""],
   ["","","","9","","","","",""],
   ["","","","","2","","9","","8"],
   ["","1","","8","","","","","3"]]), gap(),
 table([700,700,700,700,700,700,700,700,700],
  [["7","6","2","3","8","5","4","9","1"],
   ["5","4","1","6","9","2","8","3","7"],
   ["9","3","8","4","1","7","6","5","2"],
   ["8","2","5","1","7","4","3","6","9"],
   ["1","7","6","5","3","9","2","8","4"],
   ["3","9","4","2","6","8","7","1","5"],
   ["4","8","7","9","5","3","1","2","6"],
   ["6","5","3","7","2","1","9","4","8"],
   ["2","1","9","8","4","6","5","7","3"]]), gap(),
 lead("Verification.","Three checks, none of which reuses the solver. Every row, every column and every 3×3 block is a permutation of 1 through 9. Every one of the 22 given clues is preserved in the solution. And the instance is uniquely solvable: adding the no-good cut"),
 eq([sum(`(r,c)`,[sub("x","r,c,v*(r,c)")]), mr(` ${LE} 80`)]),
 body("where v*(r,c) is the digit found above, forbids that one assignment while leaving every other completion available. Re-solving with that cut returns infeasible, which proves no second solution exists. This is a cheap and general technique: it converts “I found a solution” into “I found the only solution” for one extra solve."),
);

// =============================================== EP1
P(brk(), h1("EP1.  Total Unimodularity and the Shortest-Path Relaxation"),
 body("A matrix is totally unimodular (TU) when every square submatrix has determinant 0, +1 or −1. The condition applies at every order, not only to the full matrix, and a submatrix means any selection of rows and columns. Since each single entry is itself a submatrix of order one, all entries of a TU matrix lie in {0, +1, −1}."),
 body("The link to integrality runs through Cramer's rule. A vertex of a polyhedron is determined by a square nonsingular subsystem Bx = d, so its coordinates are ratios of determinants with det(B) in every denominator. When det(B) is ±1 and d is integral, the vertex has integer coordinates. Hoffman and Kruskal (1956) proved the sharp version: for an integral matrix A, the polyhedron {x : Ax ≤ b, x ≥ 0} has only integral vertices for EVERY integral b if and only if A is totally unimodular. The condition is necessary as well as sufficient."),
 lead("The incidence matrix is TU.","The shortest-path constraint matrix is the node-arc incidence matrix: rows indexed by nodes, columns by arcs, +1 in the tail row, −1 in the head row, 0 elsewhere. Each column holds exactly one +1 and one −1. Induction on the order k of a square submatrix B. For k = 1 the single entry is 0, ±1 by construction. For k > 1, three cases exhaust the possibilities. If some column of B is all zero, det(B) = 0. If some column has exactly one nonzero entry, expanding along it gives ±1 times a determinant of order k − 1, which lies in {0, ±1} by hypothesis. Otherwise every column of B holds both a +1 and a −1, so every column sums to zero, the rows of B sum to the zero vector, B is singular, and det(B) = 0. Every case lands in {0, +1, −1}."),
 lead("Why the relaxation is exact.","The shortest-path constraints are flow conservation, whose matrix is exactly this incidence matrix, together with bounds 0 ≤ x ≤ 1. Appending an identity block for the bounds preserves total unimodularity. The right-hand side is integral: +1 at s, −1 at t, 0 elsewhere, with bounds 0 and 1. Hoffman and Kruskal therefore apply, every vertex of the relaxed polytope is integral, and since a bounded linear program attains its optimum at a vertex, the simplex method returns a binary solution without being asked. The integer program and its relaxation share an optimal value. This is what Problem 2 measured: zero gap on all ten instances, no fractional arc value anywhere, and at most one branch-and-bound node."),
 lead("Where it fails.","The property is fragile. The vertex-edge incidence matrix of an undirected odd cycle is the standard counterexample: for a triangle it has determinant 2, outside {0, ±1}. The longest-path model of Problem 2 inherits failures of this kind, which is why its relaxation is not exact and why branch and bound with generated constraints is required there. Checking every square submatrix is exponential, so usable criteria matter; Ghouila-Houri (1962) gives a characterization by row partition, and interval matrices, network matrices and bipartite incidence matrices are the standard TU families worth recognizing on sight."),
 body("Numerically, for the six-node nine-arc network used in the Part 1 write-up, enumerating all square submatrices at every order from 1 to 6 gives 5,004 determinants, all in {0, +1, −1}, with worst deviation exactly zero. That confirms the theorem on one matrix; it does not prove it, which is what the induction above is for."),
);

// =============================================== EP2
P(brk(), h1("EP2.  The Vitali Set and the Need for σ-Algebras"),
 body("Lebesgue measure on the real line is asked to satisfy four properties at once: it assigns λ([a,b]) = b − a, it is translation invariant, it is countably additive on disjoint sets, and it is defined for every subset of ℝ. The Vitali set shows these four are jointly inconsistent."),
 lead("Construction.","On [0,1) define x ~ y when x − y is rational. This is an equivalence relation, and each class is countable and dense in [0,1), so there are uncountably many classes. Using the Axiom of Choice, select exactly one representative from each class and call the resulting set ν."),
 lead("Why ν cannot have a measure.","Enumerate the rationals in [−1,1] as q₁, q₂, … and let νₙ = ν + qₙ be the translates. These are pairwise disjoint: if v + qᵢ = w + qⱼ then v − w is rational, so v and w lie in the same class, so v = w by construction, so qᵢ = qⱼ. They also sandwich the unit interval: every x in [0,1) differs from its class representative by a rational in [−1,1], so [0,1) ⊆ ∪ₙ νₙ ⊆ [−1,2)."),
 body("Suppose ν were measurable, with λ(ν) = m. Translation invariance gives λ(νₙ) = m for every n, and countable additivity gives λ(∪ₙ νₙ) = Σₙ m. Two cases, both impossible. If m = 0 the union has measure 0, yet it contains [0,1) of measure 1. If m > 0 the union has measure ∞, yet it sits inside [−1,2) of measure 3. No value of m works, so ν is not Lebesgue measurable."),
 lead("What has to be given up.","The contradiction used all four properties, so at least one must go. Normalization is what measure means and cannot go. Translation invariance is the defining symmetry of length. Countable additivity is what separates measure theory from finitely additive content and is what makes limit theorems work. The remaining property is the one abandoned: a measure need not be defined on every subset. Note that the construction requires the Axiom of Choice, and this is not incidental. Solovay (1970) showed that ZF with dependent choice is consistent with the statement that every set of reals is Lebesgue measurable, so no explicit non-measurable set can be exhibited without some form of choice."),
 lead("Why this forces σ-algebras.","Restricting the domain is only coherent if the restricted collection is closed under the operations measure theory actually performs. Those operations are complementation and countable union, and closure under exactly those is the definition of a σ-algebra ℱ. This is why a probability space is the triple (Ω, ℱ, ℚ) rather than just a sample space and a number-valued function: ℱ names which events are permitted to have probabilities. Countable rather than finite closure is essential, because limits, tail events and the convergence theorems all require countably many operations."),
 lead("Consequence for this course.","Expectation is a pairing between a random variable and a measure, and the pairing is only defined when both live on the same σ-algebra: the variable must be ℱ-measurable and the measure defined on ℱ. Every construction that follows depends on this. Value-at-Risk needs the distribution function to be well defined; Conditional Value-at-Risk needs conditional expectation, which is defined as a Radon-Nikodym derivative with respect to a sub-σ-algebra and has no meaning without one; distributionally robust optimization ranges over a set of probability measures, which presupposes a fixed ℱ on which they are all defined. The Vitali set is the reason that bookkeeping is mandatory rather than pedantic."),
);

// ----------------------------------------------------------------- build
const doc = new Document({
  creator: "Lidivine Kengne",
  title: "IE 5311 Homework Solutions",
  styles: { default: { document: { run: { font: H.BODY, size: H.SZ, color: "000000" } } } },
  sections: [{ properties: { page: { size: { width: 12240, height: 15840 },
    margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } }, children: ch }],
});
Packer.toBuffer(doc).then(b => { fs.writeFileSync(process.argv[2], b);
  console.log("written", process.argv[2], b.length, "bytes"); });
